# Cheatsheets and handouts {.unnumbered}

This section contains a single-page rendering of slides introducing some
chapters in form of handouts. These are intended for easier reference
during practical exercise sessions for each relevant chapter.

Additionally, exercises for some chapters (namely on fundamentals of
R programming, _tidyverse_, and _ggplot2_) are supported by a set of
beautiful cheatsheets. These contain everything needed as a reference
for all exercises, but also much, much more than that. Keep them on your
desk as you beging working on your own projects!

## PDF cheatsheets

- **"R bootcamp session"** -- [cheatsheet on **base R**](cheatsheets/base-r.pdf),
[cheatsheet on **RStudio**](cheatsheets/rstudio.pdf)
- **"Introduction to _tidyverse_" and "More _tidyverse_ practice"** -- [cheatsheet on the **_dplyr_** package](cheatsheets/dplyr.pdf)
- **"Visualization with _ggplot2_"** -- [cheatsheet on the **_ggplot2_** package](cheatsheets/ggplot2.pdf)
- **"Quarto reports and slides"** -- [cheatsheet on the **Quarto** framework](cheatsheets/quarto.pdf)

## Slide handouts

- **"R bootcamp"** -- [one-page handouts](https://bodkan.net/simgen/handouts_r-bootcamp.html)
- **"Introduction to _tidyverse_"** -- [one-page handouts](https://bodkan.net/simgen/handouts_tidy-basics.html)
- **"Visualization with _ggplot2_"** -- [one-page handouts](https://bodkan.net/simgen/handouts_tidy-viz.html)
- **"Simulations with _slendr_"** -- [one-page handouts](https://bodkan.net/simgen/handouts_slendr.html)