# Quarto reports and slides

## Introduction

From the previous section, you have now set up a proper computational project
structure. You've added your pipeline R scripts which download, manipulate,
filter, and otherwise process "raw data" into "processed data", the latter
being the starting point of data analysis, visualization, and statistical
inference. You've also learned to write standalone scripts to do all of that.

**Honestly, what you've learned in the previous chapter on general R project
setup is everything you might need to get through a Master's project or even
a PhD. To reiterate:**

1. **You're data processing code is now fully automated and completely reproducible.**

2. **You can also generate results, figures, and summaries in an equally
automated way.**

**In principle, you don't need anything else beyond nicely organized scripts
which produce results (tables, figures, etc.) in an equally organized way.**

**In this session, you will learn about another possibility of doing 
reproducible data science. Not a replacement for the previous script-based
workflows, but a complementary approach to doing the same thing. I personally
use both approaches.**

**Let's introduce the [Quarto system](https://quarto.org) for reproducible
scientific research. First, please take a moment to watch
[this wonderful presentation](https://www.youtube.com/watch?v=_f3latmOhew)**
(you can stop watching by about 15 minutes, when the discussion turns to
building websites).

---

## Exercise 1: Creating a reproducible report

The previous exercises were focused on our metadata and IBD data, and turning
our disorganized pile of code into proper project structure.

In this session, we'll do a similar thing, but focus instead on the
analysis of Neanderthal proportions in a time-series of aDNA individuals from
Europe [discussed here](https://bodkan.net/simgen/tidy-viz.html#part-2-practicing-visualization-on-time-series-data).

**First create a new blank Quarto document by doing the following:**

1. Click on `File` `->` `New File` `->` `Quarto Document...`.
2. Click on `Create Empty Document`.
3. Save the file under `notebooks/neand_ancestry.qmd`.

(I like to call what we'll be creating as "a notebook", because it's very
similar to a normal lab notebook).

---

**In your new Quarto file, first make sure you have the "Source" view turned
on (top left of your editor window). For now at least, you will want to switch
to "Visual" when you start writing!**

---

**Paste in the following template (just to save you a lot of annoying typing):**

::: {.callout-note collapse="true" icon=false}
#### Click to reveal code to be added to your Quarto document

```{bash}
#| echo: false
cat files/repro/neand_ancestry.qmd
```

:::

---

**Click on the `"=> Render"` button on top of your editor window and see the
magic happen!**

---

**You can also check the `"Render on Save"` box on top of your editor window.
See what happens when you save the document using CTRL / CMD + S. This can
slow things down for long-running analyses, but is very convenient otherwise.**

---






## Exercise XYZ: Recording R session information

**The following command should be included at the end of your "Quarto reports".
When you run it, how would you read and interpret the information it provides?
What do you think is the most important information which might be missing in
case you need to pick up someone else's project or script?**

```{r}
sessionInfo()
```





## Further practice

### Option 1: Your own data

I'm sure you have done some form of table munging and data visualization in your
projects. If you're done with the exercises above, here are some ideas for you:

1. If you haven't used R for processing of tabular data in your work -- maybe
you have done similar table munging in Excel or Google Sheets in a manual
(i.e., non-reproducible) way? -- write your processing steps as a self-contained
R script:

- If you used Excel, you can use the R package [_readxl_](https://readxl.tidyverse.org),
- If you used Google Sheets, you can use the R package [_googlesheets4_](https://googlesheets4.tidyverse.org)

2. If you used Excel or base R for plotting figures, use what you learned
about _ggplot2_ to make beautiful, publication-ready plots as we did in our
exercises.

Yes, this will put you in an uncharted territory. This is scary and totally
normal when doing research. I'm happy to help you out with questions
and issues!
