# Resources {.unnumbered}

This section contains a single-page rendering of slides introducing some
chapters in form of handouts, as well as the slides themselves. These are
intended for easier reference during practical exercise sessions for each
relevant chapter.

Additionally, exercises for some chapters (namely on fundamentals of
R programming, _tidyverse_, and _ggplot2_) are supported by a set of
beautiful cheatsheets. These contain everything needed as a reference
for all exercises, but also much, much more than that. Keep them on your
desk as you beging working on your own projects!

## Slides and handouts

- **"R bootcamp"** -- [slides](rendered/slides_r-bootcamp.html), [handout](rendered/handout_r-bootcamp.html)

- **"Introduction to _tidyverse_"** -- [slides](rendered/slides_tidy-basics.html), [handout](rendered/handout_tidy-basics.html) 

- **"Visualization with _ggplot2_"** -- [slides](rendered/slides_tidy-viz.html), [handout](rendered/handout_tidy-viz.html)

- **"Simulations with _slendr_"** -- [slides](rendered/slides_slendr.html), [handout](rendered/handout_slendr.html)

## Cheatsheets

Here are links to a couple of cheatsheets useful for day-to-day work in R. See many more cheatsheets at [this link](https://opensource.posit.co/resources/cheatsheets/).

- **"R bootcamp session"** -- [cheatsheet on **base R**](cheatsheets/base-r.pdf),
[cheatsheet on **RStudio**](cheatsheets/rstudio.pdf)
- **"Introduction to _tidyverse_" and "More _tidyverse_ practice"** -- [cheatsheet on the **_dplyr_** package](cheatsheets/dplyr.pdf)
- **"Visualization with _ggplot2_"** -- [cheatsheet on the **_ggplot2_** package](cheatsheets/ggplot2.pdf)
- **"Quarto reports and slides"** -- [cheatsheet on the **Quarto** framework](cheatsheets/quarto.pdf)

