---
filters: 
 - collapse-callout.lua
---

# Installation and setup {.unnumbered}

The easiest way to set up everything on your computer is to download all of
the book materials (text, code, data, everything) to your machine
by following these steps:

1. **Clone the repository with the course materials**. In a shell terminal on
Linux or macOS, in your home directory (or anywhere else, really) you can run:

    ```         
    $ git clone https://github.com/bodkan/simgen ~/simgen
    ```

(For Windows users only: You should be able to do all of this on Windows too, but
that would require you having some kind of Linux environment (terminal, R, etc.)
already set up. Unfortunately I don't know much about that so my recommendation
is that, if you do use Windows, just do the exercises on the cloud instance
provided by the course organizers.)

2. **Install all R package dependencies** by going into the activity repository
directory you just cloned and installing the necessary R packages by following
these steps:

- First **go into the project directory you just cloned**:

    ```         
    $ cd ~/simgen
    ```

- **Open the R terminal in that directory**. You should get a note that the _renv_
package is being automatically setup, like this:

    ```         
    $ R

    [... R startup information stuff ...]

    # Bootstrapping renv 1.0.11 --------------------------------------------------
    - Downloading renv ... OK
    - Installing renv  ... OK

    - Project '~/simgen' loaded. [renv 1.0.11]
    - One or more packages recorded in the lockfile are not installed.
    - Use `renv::status()` for more details.
    ```

- **Install R package dependencies** (still in the R console!):

    ```         
    > renv::restore(prompt = FALSE)
    ```

-   **Set up the Python environment** used by the _slendr_ R package for simulation
and tree-sequence analysis (still in the R console!):

    ```         
    > slendr::setup_env(agree = TRUE)
    ```

    If everything worked, you should get an optimistic message saying:

    ```         
    ======================================================================
    Python environment for slendr has been successfuly created, and the R
    interface to msprime, tskit, and pyslim modules has been activated.

    In future sessions, activate this environment by calling init_env().
    =======================================================================
    ```

4. **Open the repository directory in RStudio** (on your laptop if you cloned
the repository there, or in your browser if you're using the provided cloud
instance) and navigate to the book repository directory via `File -> Open Project...`
in the RStudio menu, opening the `simgen.Rproj` file.

**If the `setup_env()` installation procedure fails, try the following:**

1. Delete the failed installation attempt:

```         
slendr::clear_env(force = TRUE, all = TRUE)
```

2. Try installing it again, this time using `pip` as a Python installation method (the default is `conda` which unfortunately fails fairly often):

```         
slendr::setup_env(agree = TRUE, pip = TRUE)
```







