---
format:                         ### slides
  revealjs:                     ### slides
    echo: true                  ### slides
    code-line-numbers: false    ### slides
    fig-align: center           ### slides
    slide-number: true          ### slides
    self-contained: true        ### slides
---

# R bootcamp

## Useful shortcuts

- the challenge is that I have no idea what level you are at
- the problems and exercises are very very easy for me, but I write R for a living
- if they are trivial for you, still please try to go through them (maybe you
can give me comments on how I can improve them)
  - then pick a chapter in the incredible Advanced R text book, do
  a quiz at the beginning of that chapter
  - if you don't know all answers, study that chapter and do the exercises
  - this book is very advanced though, and really targetted at people who
  build software using R (a higher category of coding then data analysis)


## How R is typically taught

Most university courses completely skip "the programming language part"

Usually immediately jump into fitting linear models, running t-tests, plotting data, etc.

. . .

This reinforces the "R is nothing but a calculator language".

. . .

But worse, it treats R and its tools as a blackbox.

. . .

This is a disaster once bugs and issues come in (and they always do when we program)...

... because how do you troubleshoot a blackbox?
