<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Working with tables – Simulation-Based Population Genomics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tidy-ggplot.html" rel="next">
<link href="./r-bootcamp.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./tidy-tables.html">Welcome to tidyverse</a></li><li class="breadcrumb-item"><a href="./tidy-tables.html"><span class="chapter-title">Working with tables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Simulation-Based Population Genomics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R language</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-bootcamp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R bootcamp</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Welcome to tidyverse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidy-tables.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Working with tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidy-ggplot.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Reproducible computing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repro-proj.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structuring projects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repro-cli.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Command-line scripts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repro-quarto.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Quarto reports and slides</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Spatial data science</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial-sf.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial data science</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Modeling fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./popgen-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Demographic models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./popgen-stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tree-sequence statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./popgen-nonspatial-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exploring PCA patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./popgen-spatial-pca.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./popgen-tracts-dating.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Admixture tracts and dating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./popgen-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Natural selection</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Simulation-based inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-afs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title"><span class="math inline">\(N_e\)</span> inference with AFS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-thinking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Algorithmic thinking</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./handouts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Handouts</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handouts_slendr.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introduction to <em>slendr</em></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slides.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Slides</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-selection-of-data-frame-inspection-functions" id="toc-a-selection-of-data-frame-inspection-functions" class="nav-link active" data-scroll-target="#a-selection-of-data-frame-inspection-functions">A selection of data-frame inspection functions</a></li>
  <li><a href="#exercise-1-familiarization-with-new-data" id="toc-exercise-1-familiarization-with-new-data" class="nav-link" data-scroll-target="#exercise-1-familiarization-with-new-data">Exercise 1: Familiarization with new data</a></li>
  <li><a href="#exercise-2-selecting-columns" id="toc-exercise-2-selecting-columns" class="nav-link" data-scroll-target="#exercise-2-selecting-columns">Exercise 2: Selecting columns</a></li>
  <li><a href="#exercise-3-filtering-rows" id="toc-exercise-3-filtering-rows" class="nav-link" data-scroll-target="#exercise-3-filtering-rows">Exercise 3: Filtering rows</a></li>
  <li><a href="#exercise-4-the-pipe" id="toc-exercise-4-the-pipe" class="nav-link" data-scroll-target="#exercise-4-the-pipe">Exercise 4: The pipe <code>%&gt;%</code></a></li>
  <li><a href="#exercise-5-more-complex-conditions" id="toc-exercise-5-more-complex-conditions" class="nav-link" data-scroll-target="#exercise-5-more-complex-conditions">Exercise 5: More complex conditions</a></li>
  <li><a href="#exercise-6-dropping-columns" id="toc-exercise-6-dropping-columns" class="nav-link" data-scroll-target="#exercise-6-dropping-columns">Exercise 6: Dropping columns</a></li>
  <li><a href="#exercise-7-renaming-columns" id="toc-exercise-7-renaming-columns" class="nav-link" data-scroll-target="#exercise-7-renaming-columns">Exercise 7: Renaming columns</a></li>
  <li><a href="#exercise-8-reorganizing-columns" id="toc-exercise-8-reorganizing-columns" class="nav-link" data-scroll-target="#exercise-8-reorganizing-columns">Exercise 8: Reorganizing columns</a></li>
  <li><a href="#exercise-9-sorting-tables" id="toc-exercise-9-sorting-tables" class="nav-link" data-scroll-target="#exercise-9-sorting-tables">Exercise 9: Sorting tables</a></li>
  <li><a href="#exercise-10-mutating-tables" id="toc-exercise-10-mutating-tables" class="nav-link" data-scroll-target="#exercise-10-mutating-tables">Exercise 10: Mutating tables</a></li>
  <li><a href="#exercise-12-summarizing-tables" id="toc-exercise-12-summarizing-tables" class="nav-link" data-scroll-target="#exercise-12-summarizing-tables">Exercise 12: Summarizing tables</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./tidy-tables.html">Welcome to tidyverse</a></li><li class="breadcrumb-item"><a href="./tidy-tables.html"><span class="chapter-title">Working with tables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Working with tables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Before we begin, let’s introduce the two important parts of the <em>tidyverse</em> ecosystem, which we will be using extensively during exercises in this chapter.</p>
<ol type="1">
<li><p><a href="https://dplyr.tidyverse.org"><em>dplyr</em></a> is a centerpiece of the entire R data science universe, providing important functions for data manipulation, data summarization, and filtering of tabular data;</p></li>
<li><p><a href="https://tidyr.tidyverse.org"><em>tidyr</em></a> is an R package which helps us morph untidy data into tidy data frames;</p></li>
<li><p><a href="https://readr.tidyverse.org"><em>readr</em></a> is an R package which provides very convenient functions for reading (and writing) tabular data. Think of it as a set of better alternatives to base R functions such as <code>read.table()</code>, etc. (Another very useful package is <a href="https://readxl.tidyverse.org"><em>readxl</em></a> which is useful for working with Excel data).</p></li>
</ol>
<p>Every single script you will be writing in this session will begin with these two lines of code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s also introduce a second star in this session, our example data set. The following command will read a metadata table with information about individuals published in a recent aDNA paper on the history or the Holocene in West Eurasia, dubbed “MesoNeo” (<a href="https://www.nature.com/articles/s41586-023-06865-0">reference</a>). We use the <code>read_tsv()</code> function (from the above-mentioned <em>readr</em> package) and store it in a variable <code>df</code>. Everything in the section on <em>tidyverse</em> will revolve around working with this data because it represents an excellent example of this kind of metadata table you will find across the entirety of computational population genomics. (Yes, this function is quite magical – it can read stuff from a file stored on the internet. If you’re curious about the file itself, just paste the URL address in your browser.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"https://tinyurl.com/qwe-asd-zxc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Create a new R script in RStudio, (<code>File</code> <code>-&gt;</code> <code>New file</code> <code>-&gt;</code> <code>R Script</code>) and save it somewhere on your computer as <code>tidy-tables.R</code> (<code>File</code> -&gt; <code>Save</code>). Put the <code>library()</code> calls and the <code>read_tsv()</code> command above in this script, and let’s get started!</strong></p>
<section id="a-selection-of-data-frame-inspection-functions" class="level2">
<h2 class="anchored" data-anchor-id="a-selection-of-data-frame-inspection-functions">A selection of data-frame inspection functions</h2>
<p>Whenever you get a new source of data, like a table from a collaborator, data sheet downloaded from supplementary materials of a paper, you need to familiarize yourself with it before you do anything else. Here is a list of functions that you will be using constantly when doing data science to answer basic questions: Use this list as a cheatsheet of sorts! <strong>Also, use <code>?&lt;function&gt;</code> to look up their documentation to see the possibilities for options and additional features.</strong></p>
<ol type="1">
<li><p><em>“How many observations (rows) and variables (columns) does my data have?”</em> – <code>nrow()</code>, <code>ncol()</code></p></li>
<li><p><em>“What variable (column) names am I going to be working with?”</em> – <code>colnames()</code></p></li>
<li><p><em>“What data types (numbers, strings, logicals, etc.) does it contain?”</em> – <code>str()</code>, or better, <code>glimpse()</code></p></li>
<li><p><em>“How can I take a quick look at a subset of the data?”</em> – <code>head()</code>, <code>tail()</code></p></li>
<li><p><em>“For a specific variable column, what is the distribution of values I can expect in that column?”</em> – <code>table()</code> for “discrete types”, <code>summary()</code> for “numeric types”, <code>min()</code>, <code>max()</code>, <code>which.min()</code>, <code>which.max()</code></p></li>
</ol>
<p><strong>Before we move on, note that when you type <code>df</code> into your R console, you will see a slightly different format of the output than when we worked with plain R data frames in the previous chapter. This format of data frame data is called a <a href="https://tibble.tidyverse.org">“tibble”</a> and represents <em>tidyverse</em>’s more user friendly and modern take on data frames. For almost all practical purposes, from now on, we’ll be talking about <em>tibbles</em> as data frames.</strong></p>
</section>
<section id="exercise-1-familiarization-with-new-data" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-familiarization-with-new-data">Exercise 1: Familiarization with new data</h2>
<p><strong>Inspect the <code>df</code> metadata using the functions above, and try to answer the following questions using the functions from the list above (you should decide which will be appropriate for which question).</strong></p>
<p><strong>Before you use one of these functions for the first time, take a moment to skim through its <code>?function_name</code>.</strong></p>
<ol type="1">
<li><strong>How many individuals do we have metadata for?</strong></li>
</ol>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Number of rows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4172</code></pre>
</div>
</div>
<p>Number of <code>unique()</code> sample IDs (this should ideally always give the same number, but there’s never enough sanity checks in data science):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(df<span class="sc">$</span>sampleId))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4172</code></pre>
</div>
</div>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>What data types do the variables in our data have?</strong></li>
</ol>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Column names function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "sampleId"         "popId"            "site"             "country"         
 [5] "region"           "groupLabel"       "groupAge"         "flag"            
 [9] "shapeA"           "colorA"           "latitude"         "longitude"       
[13] "callset"          "dataSource"       "age14C"           "ageHigh"         
[17] "ageLow"           "ageAverage"       "datingSource"     "coverage"        
[21] "sex"              "hgMT"             "gpAvg"            "ageRaw"          
[25] "clusterId"        "clusterIBDGlobal" "clusterIBDFine"   "hgYMajor"        
[29] "hgYMinor"         "color"            "clusterAlias"     "shape"           </code></pre>
</div>
</div>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>What data types (numbers, strings, logicals, etc.) are our variables of?</strong></li>
</ol>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>I tend to use <code>str()</code> because I’m old and very used to it, but <code>glimpse()</code> is new and better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [4,172 × 32] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ sampleId        : chr [1:4172] "NA18486" "NA18488" "NA18489" "NA18498" ...
 $ popId           : chr [1:4172] "YRI" "YRI" "YRI" "YRI" ...
 $ site            : chr [1:4172] NA NA NA NA ...
 $ country         : chr [1:4172] "Nigeria" "Nigeria" "Nigeria" "Nigeria" ...
 $ region          : chr [1:4172] "WestAfrica" "WestAfrica" "WestAfrica" "WestAfrica" ...
 $ groupLabel      : chr [1:4172] "YRI" "YRI" "YRI" "YRI" ...
 $ groupAge        : chr [1:4172] "Modern" "Modern" "Modern" "Modern" ...
 $ flag            : chr [1:4172] "0" "0" "0" "0" ...
 $ shapeA          : num [1:4172] 0 0 0 0 0 0 0 0 0 0 ...
 $ colorA          : chr [1:4172] NA NA NA NA ...
 $ latitude        : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ longitude       : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ callset         : chr [1:4172] "sg.diploid" "sg.diploid" "sg.diploid" "sg.diploid" ...
 $ dataSource      : chr [1:4172] "1000g" "1000g" "1000g" "1000g" ...
 $ age14C          : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ ageHigh         : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ ageLow          : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ ageAverage      : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ datingSource    : chr [1:4172] NA NA NA NA ...
 $ coverage        : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ sex             : chr [1:4172] "XY" "XX" "XX" "XY" ...
 $ hgMT            : chr [1:4172] NA NA NA NA ...
 $ gpAvg           : num [1:4172] NA NA NA NA NA NA NA NA NA NA ...
 $ ageRaw          : chr [1:4172] NA NA NA NA ...
 $ clusterId       : chr [1:4172] NA NA NA NA ...
 $ clusterIBDGlobal: chr [1:4172] "Africa_modern" "Africa_modern" "Africa_modern" "Africa_modern" ...
 $ clusterIBDFine  : chr [1:4172] "YRI" "YRI" "YRI" "YRI" ...
 $ hgYMajor        : chr [1:4172] NA NA NA NA ...
 $ hgYMinor        : chr [1:4172] NA NA NA NA ...
 $ color           : chr [1:4172] "yellow4" "yellow4" "yellow4" "yellow4" ...
 $ clusterAlias    : chr [1:4172] "Africa_modern" "Africa_modern" "Africa_modern" "Africa_modern" ...
 $ shape           : num [1:4172] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "spec")=
  .. cols(
  ..   sampleId = col_character(),
  ..   popId = col_character(),
  ..   site = col_character(),
  ..   country = col_character(),
  ..   region = col_character(),
  ..   groupLabel = col_character(),
  ..   groupAge = col_character(),
  ..   flag = col_character(),
  ..   shapeA = col_double(),
  ..   colorA = col_character(),
  ..   latitude = col_double(),
  ..   longitude = col_double(),
  ..   callset = col_character(),
  ..   dataSource = col_character(),
  ..   age14C = col_double(),
  ..   ageHigh = col_double(),
  ..   ageLow = col_double(),
  ..   ageAverage = col_double(),
  ..   datingSource = col_character(),
  ..   coverage = col_double(),
  ..   sex = col_character(),
  ..   hgMT = col_character(),
  ..   gpAvg = col_double(),
  ..   ageRaw = col_character(),
  ..   clusterId = col_character(),
  ..   clusterIBDGlobal = col_character(),
  ..   clusterIBDFine = col_character(),
  ..   hgYMajor = col_character(),
  ..   hgYMinor = col_character(),
  ..   color = col_character(),
  ..   clusterAlias = col_character(),
  ..   shape = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,172
Columns: 32
$ sampleId         &lt;chr&gt; "NA18486", "NA18488", "NA18489", "NA18498", "NA18499"…
$ popId            &lt;chr&gt; "YRI", "YRI", "YRI", "YRI", "YRI", "YRI", "YRI", "YRI…
$ site             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ country          &lt;chr&gt; "Nigeria", "Nigeria", "Nigeria", "Nigeria", "Nigeria"…
$ region           &lt;chr&gt; "WestAfrica", "WestAfrica", "WestAfrica", "WestAfrica…
$ groupLabel       &lt;chr&gt; "YRI", "YRI", "YRI", "YRI", "YRI", "YRI", "YRI", "YRI…
$ groupAge         &lt;chr&gt; "Modern", "Modern", "Modern", "Modern", "Modern", "Mo…
$ flag             &lt;chr&gt; "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"…
$ shapeA           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ colorA           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ latitude         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ longitude        &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ callset          &lt;chr&gt; "sg.diploid", "sg.diploid", "sg.diploid", "sg.diploid…
$ dataSource       &lt;chr&gt; "1000g", "1000g", "1000g", "1000g", "1000g", "1000g",…
$ age14C           &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ageHigh          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ageLow           &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ageAverage       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ datingSource     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ coverage         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ sex              &lt;chr&gt; "XY", "XX", "XX", "XY", "XX", "XY", "XX", "XY", "XX",…
$ hgMT             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ gpAvg            &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ageRaw           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ clusterId        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ clusterIBDGlobal &lt;chr&gt; "Africa_modern", "Africa_modern", "Africa_modern", "A…
$ clusterIBDFine   &lt;chr&gt; "YRI", "YRI", "YRI", "YRI", "YRI", "YRI", "YRI", "YRI…
$ hgYMajor         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ hgYMinor         &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ color            &lt;chr&gt; "yellow4", "yellow4", "yellow4", "yellow4", "yellow4"…
$ clusterAlias     &lt;chr&gt; "Africa_modern", "Africa_modern", "Africa_modern", "A…
$ shape            &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>What is the distribution of dates of aDNA individuals? What are the variables we have that describe the ages (maybe look at those which have “age” in their name)? Which one would you use to get information about the ages of most individuals?</strong></li>
</ol>
<p><strong>Hint:</strong> Remember that for a column/vector <code>df$&lt;variable&gt;</code>, <code>is.na(df$&lt;variable&gt;)</code> gives you <code>TRUE</code> for each <code>NA</code> element in that column variable, and <code>sum(is.na(df$&lt;variable&gt;))</code> counts the number of <code>NA</code>. Alternatively, <code>mean(is.na(df$&lt;variable&gt;))</code> counts the proportion of <code>NA</code> values!</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>From <code>colnames(df)</code> above we see a number of columns which seem to have something todo with “age”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">colnames</span>(df)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># don't worry about this weird command, I'm using it to show you the relevant columns</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># -- ask me if you're interested! :)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span>(<span class="st">"^age.*|^.*Age$"</span>, columns, <span class="at">value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "groupAge"   "age14C"     "ageHigh"    "ageLow"     "ageAverage"
[6] "ageRaw"    </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>age14C))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2068552</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>ageHigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.394535</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>ageLow))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.394535</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>ageAverage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3995686</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>ageRaw))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09467881</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(df<span class="sc">$</span>groupAge)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Modern"  "Ancient" "Archaic"</code></pre>
</div>
</div>
<p>Interesting, it looks like the <code>ageAverage</code> variable has the highest proportion of non-<code>NA</code> values at about 39.96%. We also seem to have another column, <code>groupAge</code> which clusters individuals into three groups. We’ll stick to these two variables whenever we have a question regarding a date of an individual.</p>
</div>
</div>
</div>
<ol start="4" type="1">
<li><strong>How many ancient individuals do we have? How many “modern” (i.e., present-day humans) individuals?</strong></li>
</ol>
<p><strong>Hint:</strong> Use the fact that for any vector (and <code>df$groupAge</code> is a vector, remember!), we can get the number of elements of that vector matching a certain value by applying the <code>sum()</code> function on a “conditional” expression, like <code>df$groupAge == "Ancient"</code> which, on its own, gives <code>TRUE</code> / <code>FALSE</code> vector.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>which_ancient <span class="ot">&lt;-</span> df<span class="sc">$</span>groupAge <span class="sc">==</span> <span class="st">"Ancient"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(which_ancient)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(which_ancient)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1665</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>which_modern <span class="ot">&lt;-</span> df<span class="sc">$</span>groupAge <span class="sc">==</span> <span class="st">"Modern"</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(which_modern)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2504</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>which_archaic <span class="ot">&lt;-</span> df<span class="sc">$</span>groupAge <span class="sc">==</span> <span class="st">"Archaic"</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(which_archaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
</div>
</div>
</div>
<ol start="5" type="1">
<li><strong>Who are the mysterious “Archaic” individuals (column <code>groupAge</code>)?</strong></li>
</ol>
<p><strong>Hint:</strong> We need to <em>filter</em> our table down to rows which have <code>groupAge == "Archaic"</code>. This is an indexing operation which you learned about in the R bootcamp session! Remember that data frames can be indexed into along two dimensions: rows and columns. You want to filter by the rows here.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Again, this gets us a logical vector which has <code>TRUE</code> for each element corresponding to an “Archaic” individual (whoever that might be):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>which_archaic <span class="ot">&lt;-</span> df<span class="sc">$</span>groupAge <span class="sc">==</span> <span class="st">"Archaic"</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(which_archaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
</div>
<p>And we can then use this vector as an index into our overall data frame, just like we learned in the bootcamp session:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>archaic_df <span class="ot">&lt;-</span> df[which_archaic, ]</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>archaic_df<span class="sc">$</span>sampleId</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Vindija33.19"    "AltaiNeandertal" "Denisova"       </code></pre>
</div>
</div>
<p>Our mysterious “Archaic” individuals are two Neanderthals and a Denisovan!</p>
</div>
</div>
</div>
<ol start="6" type="1">
<li><strong>Do we have geographical information? Countries or geographical coordinates or both? Which countries do we have individuals from? (We’ll talk about spatial data science later in detail, so let’s interpret whatever geographical variable columns we have in our data frame <code>df</code> as any other numerical or string column variable.)</strong></li>
</ol>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Looking at <code>colnames(df)</code> we have a number of columns which have something to do with geography: <code>country</code>, <code>region</code>, and also the traditional <a href="https://en.wikipedia.org/wiki/Geographic_coordinate_system#Latitude_and_longitude"><code>longitude</code> and <code>latitude</code> coordinates</a>.</p>
<p><code>table()</code> counts the number of elements in a vector (basically, a histogram without plotting it), <code>sort()</code> then sorts those elements for easier reading:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(df<span class="sc">$</span>country), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         India          China         Russia          Italy        Nigeria 
           394            308            285            256            207 
       Denmark         Sweden             UK          Spain         Gambia 
           184            174            167            132            114 
           USA        Vietnam          Japan     PuertoRico        Finland 
           108            108            107            104            102 
        Europe          Kenya       Barbados       Pakistan       Colombia 
            99             98             96             96             94 
          Peru    SierraLeone         Mexico     Kazakhstan        Estonia 
            92             85             67             64             60 
       Ukraine         Poland         France         Norway        Hungary 
            60             56             54             42             41 
       Iceland     Kyrgyzstan         Turkey        Lebanon       Portugal 
            40             39             22             19             18 
       Ireland         Faroes        Germany      Greenland        Moldova 
            16             15             12             11             10 
 CzechRepublic   South Africa           Iran         Latvia        Romania 
             9              9              8              7              7 
       Armenia         Canada         Serbia      Argentina         Brazil 
             6              6              6              5              5 
Canary Islands       Mongolia          Chile        Georgia           Laos 
             5              5              4              4              4 
      Malaysia       Thailand   Turkmenistan         Greece       Cameroon 
             4              4              4              3              2 
     Indonesia        Croatia       Ethiopia      Lithuania     Luxembourg 
             2              1              1              1              1 
   Philippines       Slovakia    Switzerland 
             1              1              1 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(df<span class="sc">$</span>region), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      NorthernEurope            SouthAsia             EastAsia 
                 635                  489                  420 
      SouthernEurope           WestAfrica         NorthAmerica 
                 409                  406                  382 
       WesternEurope CentralEasternEurope         SouthAmerica 
                 350                  330                  200 
           NorthAsia        SouthEastAsia          CentralAsia 
                 146                  124                  107 
          EastAfrica          WesternAsia          SouthAfrica 
                  99                   59                    9 
         NorthAfrica        CentralAfrica 
                   5                    2 </code></pre>
</div>
</div>
<p>We will ignore <code>longitude</code> and <code>latitude</code> for now, because they are most useful in truly geographical data analysis setting (which we will delve into a bit later).</p>
</div>
</div>
</div>
<ol start="6" type="1">
<li><strong>What is the source of the sequences in our data set? Does it look like they all come from a single study?</strong></li>
</ol>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It looks like we have a <code>dataSource</code> column which, from the <code>glimpse()</code> result above is a character vector (a vector of “strings”). This suggests that it represents discrete categories, so let’s use the <code>table()</code> &amp; <code>sort()</code> combo again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(df<span class="sc">$</span>dataSource), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                      1000g 
                                       2504 
                      Margyaran_2020_Nature 
                                        376 
                                  thisStudy 
                                        318 
                       Antonio_2019_Science 
                                        134 
                       Damgaard_2018_Nature 
                                        131 
                      Damgaard_Science_2018 
                                         68 
                      Allentoft_Nature_2015 
                                         64 
                           Brunel_PNAS_2020 
                                         49 
                        Scheib_Science_2018 
                                         42 
            Krzewinska_ScienceAdvances_2018 
                                         28 
                         Sikora_Nature_2019 
                                         28 
               Ebenesersdottir_Science_2018 
                                         25 
                        McColl_Science_2018 
                                         25 
                        Schroeder_PNAS_2019 
                                         24 
                   Saag_CurrentBiology_2019 
                                         22 
                  Jarve_CurrentBiology_2019 
                                         21 
                    SanchezQuinto_PNAS_2019 
                                         21 
           Fernandes_ScientificReports_2018 
                                         17 
                   MorenoMayar_Science_2018 
                                         17 
             Krzewinska_CurrentBiology_2018 
                                         16 
                            Haber_AJHG_2019 
                                         14 
               Martiniano_PLoSGenetics_2017 
                                         12 
                 Malmstrom_ProcBiolSci_2019 
                                         11 
           Amorim_NatureCommunications_2018 
                                         10 
          Brace_NatureEcologyEvolution_2019 
                                         10 
        Schiffels_NatureCommunications_2016 
                                         10 
                       Valdiosera_PNAS_2018 
                                         10 
                         Veeramah_PNAS_2018 
                                         10 
            Gamba_NatureCommunications_2014 
                                          9 
       Martiniano_NatureCommunications_2016 
                                          9 
                      Raghavan_Science_2015 
                                          9 
                  Jones_CurrentBiology_2017 
                                          8 
                   Gunther_PLoSBiology_2018 
                                          7 
                 Kilinc_CurrentBiology_2016 
                                          7 
                 Lindo_ScienceAdvances_2018 
                                          7 
                   Ning_CurrentBiology_2019 
                                          7 
         GonzalesFortes_CurrentBiology_2017 
                                          6 
                    Schlebusch_Science_2017 
                                          6 
                            Haber_AJHG_2017 
                                          5 
                        Hofmanova_PNAS_2016 
                                          5 
                      Lazaridis_Nature_2014 
                                          5 
        RodriguezVarela_CurrentBiology_2017 
                                          5 
                     Broushaki_Science_2016 
                                          4 
                          Cassidy_PNAS_2016 
                                          4 
          GonzalesFortes_ProcRoyalSocB_2019 
                                          4 
                   Saag_CurrentBiology_2017 
                                          4 
                        Sikora_Science_2017 
                                          4 
            Jones_NatureCommunications_2015 
                                          3 
         Kashuba_CommunicationsBiology_2019 
                                          3 
                         Skoglund_Cell_2017 
                                          3 
                      Skoglund_Science_2014 
                                          3 
                      Allentoft_2015_Nature 
                                          2 
KanzawaKiriyama_AnthropologicalScience_2019 
                                          2 
                         Lipson_Nature_2020 
                                          2 
      Unterlander_NatureCommunications_2017 
                                          2 
                             Fu_Nature_2014 
                                          1 
                             Fu_Nature_2016 
                                          1 
               GallegoLlorente_Science_2015 
                                          1 
     GallegoLlorente_ScientificReports_2016 
                                          1 
                            gjerrild_inPrep 
                                          1 
                          Gunther_PNAS_2015 
                                          1 
           Jensen_NatureCommunications_2019 
                                          1 
                    MorenoMayar_Nature_2017 
                                          1 
                         Olalde_Nature_2014 
                                          1 
                             OlaldeMBE_2015 
                                          1 
                  Omrak_CurrentBiology_2016 
                                          1 
                               Pruefer_2017 
                                          1 
                         Prufer_Nature_2014 
                                          1 
                        Prufer_Science_2017 
                                          1 
                       Raghavan_Nature_2013 
                                          1 
                      Rasmussen_Nature_2010 
                                          1 
                      Rasmussen_Nature_2014 
                                          1 
                      Rasmussen_Nature_2015 
                                          1 
                Seguin-Orlando_Science_2014 
                                          1 
                                  st_inPrep 
                                          1 </code></pre>
</div>
</div>
<p>OK, it looks like we have most individuals (2504) from the <a href="http://www.internationalgenome.org">1000 genomes project</a>, we have 318 samples from <a href="https://www.nature.com/articles/s41586-023-06865-0">“this study”</a>, and then a bunch of individuals from a wide range of other publications. This is great because it allows us to refer individual specific results we might obtain later to the respective publications!</p>
</div>
</div>
</div>
<ol start="7" type="1">
<li><strong>What’s the distribution of coverage of the samples? Compute the <code>mean()</code> and other <code>summary()</code> statistics on the coverage information. Why doesn’t the <code>mean()</code> function work when you run it on the vector of numbers in the <code>coverage</code> column (use <code>?mean</code> to find the solution). Which individuals have missing coverage? Finally, use the <code>hist()</code> function to visualize this information.</strong></li>
</ol>
<p>These are all basic questions which you will be asking yourself <em>every time</em> you read a new table into R. It might not be coverage, but you will have to do this to familiarize yourself with the data and understand its potential issues!</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Mean gives us <code>NA</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>coverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>This is because computing the mean from a vector containing <code>NA</code> values is not a sensible operation – should we remove the <code>NA</code> values? It’s impossible to say in general, because that would depend on the nature of our data. Sometimes, encountering <code>NA</code> indicates a problem, so we can’t just ignore it. In situation when this is OK, there’s a argument which changes the default behavior and removes the <code>NA</code> elements before computing the mean:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>coverage, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.623036</code></pre>
</div>
</div>
<p>Summary takes care of the issue by reporting the number of <code>NA</code> values explicitly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>coverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 0.0124  0.2668  0.7812  1.6230  1.5074 58.8661    2504 </code></pre>
</div>
</div>
<p>We can see that the coverage information is missing for 2504 individuals, which is the number of individuals in the (present-day) 1000 Genomes Project data. So it makes sense, we only have coverage for the lower-coverage aDNA samples, but for present-day individuals (who have imputed genomes), the coverage does not even make sense here.</p>
<p>Let’s plot the coverage values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(df<span class="sc">$</span>coverage, <span class="at">breaks =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tidy-tables_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="8" type="1">
<li><strong>Who is the oldest individuals in our data set? Who has the highest coverage? Who has the lowest coverage?</strong></li>
</ol>
<p><strong>Hint:</strong> Use functions <code>min()</code>, <code>max()</code>, <code>which.min()</code>, <code>which.max()</code>. Look up their <code>?help</code> to understand what they do and how to use them in this context.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>which.max()</code> reports the <em>index</em> (in this case, the row number) of the maximum value in a vector (in this case, a column vector):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(df<span class="sc">$</span>ageAverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4171</code></pre>
</div>
</div>
<p>This means we can use this number to index into the data frame and find our answer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">which.max</span>(df<span class="sc">$</span>ageAverage), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 32
  sampleId    popId site  country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 AltaiNeand… Alta… Deni… Russia  North… Neanderta… Archaic  0         14 grey  
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(df<span class="sc">$</span>ageAverage, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 125000</code></pre>
</div>
</div>
<p>Let’s use the similar approach for coverage:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">which.min</span>(df<span class="sc">$</span>coverage), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 32
  sampleId popId  site    country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 NEO496   NEO496 Vasile… Ukraine Centr… Ukraine_M… Ancient  lowc…      8 black 
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(df<span class="sc">$</span>coverage, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01239792</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">which.max</span>(df<span class="sc">$</span>coverage), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 32
  sampleId popId site     country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 sf12     sf12  Stora F… Sweden  North… Sweden_Me… Ancient  0          7 grey  
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(df<span class="sc">$</span>coverage, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 58.8661</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-2-selecting-columns" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-selecting-columns">Exercise 2: Selecting columns</h2>
<p>Often times we end up in a situation in which we don’t want to have a large data frame with a huge number of columns. Not as much for the reasons of the data taking up too much memory, but for convenience. You can see that our <code>df</code> metadata table has 32 columns, which don’t fit on the screen if we just print it out:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,172 × 32
   sampleId popId site  country region   groupLabel groupAge flag  shapeA colorA
   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
 1 NA18486  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 2 NA18488  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 3 NA18489  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 4 NA18498  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 5 NA18499  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 6 NA18501  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 7 NA18502  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 8 NA18504  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
 9 NA18505  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
10 NA18507  YRI   &lt;NA&gt;  Nigeria WestAfr… YRI        Modern   0          0 &lt;NA&gt;  
# ℹ 4,162 more rows
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We can select which columns to select with the function <code>select()</code>. It has the following general format:</p>
<pre><code>select(&lt;data frame object or tibble&gt;, &lt;column 1&gt;, &lt;column 2&gt;, ...)</code></pre>
<p>This is how we would select columns using a normal base R subsetting/indexing operation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>df[, <span class="fu">c</span>(<span class="st">"sampleId"</span>, <span class="st">"region"</span>, <span class="st">"coverage"</span>, <span class="st">"ageAverage"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,172 × 4
   sampleId region     coverage ageAverage
   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;
 1 NA18486  WestAfrica       NA         NA
 2 NA18488  WestAfrica       NA         NA
 3 NA18489  WestAfrica       NA         NA
 4 NA18498  WestAfrica       NA         NA
 5 NA18499  WestAfrica       NA         NA
 6 NA18501  WestAfrica       NA         NA
 7 NA18502  WestAfrica       NA         NA
 8 NA18504  WestAfrica       NA         NA
 9 NA18505  WestAfrica       NA         NA
10 NA18507  WestAfrica       NA         NA
# ℹ 4,162 more rows</code></pre>
</div>
</div>
<p>This is the <em>tidyverse</em> approach using <code>select()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df, sampleId, region, coverage, ageAverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,172 × 4
   sampleId region     coverage ageAverage
   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;
 1 NA18486  WestAfrica       NA         NA
 2 NA18488  WestAfrica       NA         NA
 3 NA18489  WestAfrica       NA         NA
 4 NA18498  WestAfrica       NA         NA
 5 NA18499  WestAfrica       NA         NA
 6 NA18501  WestAfrica       NA         NA
 7 NA18502  WestAfrica       NA         NA
 8 NA18504  WestAfrica       NA         NA
 9 NA18505  WestAfrica       NA         NA
10 NA18507  WestAfrica       NA         NA
# ℹ 4,162 more rows</code></pre>
</div>
</div>
<p><strong>Note:</strong> The most important thing for you to note now is the absence of “double quotes”. It might not look like much, but saving yourself from having to type double quotes for every data-frame operation (like with base R) is incredibly convenient.</p>
<p><strong>Practice <code>select()</code> by creating three new data frame objects:</strong></p>
<ol type="1">
<li>Data frame <code>df_ages</code> which contains all variables related to sample ages</li>
<li>Data frame <code>df_geo</code> which contains all variables related to geography</li>
</ol>
<p>The first column of these data frames should always be <code>sampleId</code></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>df_ages <span class="ot">&lt;-</span> <span class="fu">select</span>(df, sampleId, groupAge, age14C, ageHigh, ageLow, ageAverage, ageRaw)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>df_ages</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,172 × 7
   sampleId groupAge age14C ageHigh ageLow ageAverage ageRaw
   &lt;chr&gt;    &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt; 
 1 NA18486  Modern       NA      NA     NA         NA &lt;NA&gt;  
 2 NA18488  Modern       NA      NA     NA         NA &lt;NA&gt;  
 3 NA18489  Modern       NA      NA     NA         NA &lt;NA&gt;  
 4 NA18498  Modern       NA      NA     NA         NA &lt;NA&gt;  
 5 NA18499  Modern       NA      NA     NA         NA &lt;NA&gt;  
 6 NA18501  Modern       NA      NA     NA         NA &lt;NA&gt;  
 7 NA18502  Modern       NA      NA     NA         NA &lt;NA&gt;  
 8 NA18504  Modern       NA      NA     NA         NA &lt;NA&gt;  
 9 NA18505  Modern       NA      NA     NA         NA &lt;NA&gt;  
10 NA18507  Modern       NA      NA     NA         NA &lt;NA&gt;  
# ℹ 4,162 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>df_geo <span class="ot">&lt;-</span> <span class="fu">select</span>(df, site, country, region, latitude, longitude)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>df_geo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,172 × 5
   site  country region     latitude longitude
   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;
 1 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 2 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 3 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 4 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 5 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 6 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 7 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 8 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
 9 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
10 &lt;NA&gt;  Nigeria WestAfrica       NA        NA
# ℹ 4,162 more rows</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Note that <code>select()</code> allows us to see the contents of columns of interest much easier. In a situation in which we want to analyse the geographical location of samples, we don’t want to see columns unrelated to that – <code>select()</code> helps here.</p>
<p>If your tables has many columns of interest, typing them all by hand can become tiresome real quick. <strong>Here are a few helper functions which can be very useful in that situation:</strong></p>
<ul>
<li><code>starts_with("age")</code> – matches columns starting with the string “age”</li>
<li><code>ends_with("age")</code> – matches columns ending with the string “age”</li>
<li><code>contains("age")</code> – matches columns containing the string “age”</li>
</ul>
<p><strong>Note:</strong> You can use them in place of normal column names. If we would modify our <code>select()</code> “template” above, we could do this, for instance:</p>
<pre><code>select(&lt;data frame object or tibble&gt;, starts_with("text1"), ends_with("text2"))</code></pre>
<p><strong>Check out the <code>?help</code> belonging to those functions. Note that they have <code>ignore.case = TRUE</code> set by default! It will become important soon!</strong></p>
<p><strong>Create the <code>df_ages</code> table again, with the same criteria, but use the three helper functions listed above. How many different ways of using them can you come up with to arrive at the same result?</strong></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>df_ages1 <span class="ot">&lt;-</span> <span class="fu">select</span>(df, sampleId, groupAge, age14C, ageHigh, ageLow, ageAverage, ageRaw)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>df_ages2 <span class="ot">&lt;-</span> <span class="fu">select</span>(df,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>                   sampleId,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">starts_with</span>(<span class="st">"age"</span>, <span class="at">ignore.case =</span> <span class="cn">FALSE</span>),</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">ends_with</span>(<span class="st">"Age"</span>, <span class="at">ignore.case =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-3-filtering-rows" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-filtering-rows">Exercise 3: Filtering rows</h2>
<p>In the chapter on base R, we learned how to filter rows using the indexing operation along the row-based dimension of (two-dimensional) data frames. For instance, in order to find out which individuals in the metadata are archaic, we first created a <code>TRUE</code> / <code>FALSE</code> vector of the rows corresponding to those individuals like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get a vector of the indices belonging to archaic individuals</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>which_archaic <span class="ot">&lt;-</span> df<span class="sc">$</span>groupAge <span class="sc">==</span> <span class="st">"Archaic"</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="co"># take a peek at the result to make sure we got TRUE / FALSE vector</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(which_archaic, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE</code></pre>
</div>
</div>
<p>And then we would use it to index into the data frame (in its first dimension, before the <code>,</code> comma):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>archaic_df <span class="ot">&lt;-</span> df[which_archaic, ]</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>archaic_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 32
  sampleId    popId site  country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 Vindija33.… Vind… Vind… Croatia Centr… Neanderta… Archaic  0         19 grey  
2 AltaiNeand… Alta… Deni… Russia  North… Neanderta… Archaic  0         14 grey  
3 Denisova    Deni… Deni… Russia  North… Denisova_… Archaic  0         14 grey  
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
</div>
<p>However, what if we need to filter on multiple conditions? For instance, what if we want to find only archaic individuals older than 50000 years?</p>
<p>One option would be to create multiple <code>TRUE</code> / <code>FALSE</code> vectors, each corresponding to one of those conditions, and then join them into a single logical vector by combining <code>&amp;</code> and <code>|</code> logical operators. For example, we could do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># who is archaic in our data?</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>which_archaic <span class="ot">&lt;-</span> df<span class="sc">$</span>groupAge <span class="sc">==</span> <span class="st">"Archaic"</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="co"># who is older than 50000 years?</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>which_old <span class="ot">&lt;-</span> df<span class="sc">$</span>ageAverage <span class="sc">&gt;</span> <span class="dv">50000</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="co"># who is BOTH? note the AND logical operator!</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>which_combined <span class="ot">&lt;-</span> which_archaic <span class="sc">&amp;</span> which_old</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>df[which_combined, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 32
  sampleId    popId site  country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 AltaiNeand… Alta… Deni… Russia  North… Neanderta… Archaic  0         14 grey  
2 Denisova    Deni… Deni… Russia  North… Denisova_… Archaic  0         14 grey  
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
</div>
<p>But this gets tiring very quickly, requires unnecessary amount of typing, and is very error prone. Imagine having to do this for many more conditions! The <code>filter()</code> function from <em>tidyverse</em> fixes all of these problems.</p>
<p>Again, we can rephrase the example situation with the archaics to use the new function like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df, groupAge <span class="sc">==</span> <span class="st">"Archaic"</span>, ageAverage <span class="sc">&gt;</span> <span class="dv">50000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 32
  sampleId    popId site  country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 AltaiNeand… Alta… Deni… Russia  North… Neanderta… Archaic  0         14 grey  
2 Denisova    Deni… Deni… Russia  North… Denisova_… Archaic  0         14 grey  
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
</div>
<p>A single command, very little typing, and immediately readable, almost like English! <em>“Filter data frame <code>df</code> for individuals in which column <code>groupAge</code> is”Archaic”, and who are older than 50000 years”</em>. When you think about it, it’s pretty much impossible to find a solution requiring less code.</p>
</section>
<section id="exercise-4-the-pipe" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-the-pipe">Exercise 4: The pipe <code>%&gt;%</code></h2>
<p>The pipe operator, <code>%&gt;%</code>, is the rockstar of the <em>tidyverse</em> R ecosystem, and the primary reason what makes <em>tidy</em> data approach so efficient, quick to type, and easy to read.</p>
<p>First, a bit of a general introduction: whenever you see something like <code>something</code>%&gt;%<code>f()</code>, you can read it as “take <something> and put it as the first argument of f()`”.</something></p>
<p>Why would you do this? Imagine some complex data processing operation like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h</span>(<span class="fu">f</span>(<span class="fu">g</span>(<span class="fu">i</span>(<span class="fu">j</span>(input_data)))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I.e., take <code>input_data</code>, compute <code>j(input_data)</code>, then compute <code>i()</code> on <em>that</em>, so <code>i(j(input_data))</code>, then compute <code>g(i(j(input_data)))</code>, etc. Of course this is a ridiculous example but it is not that far off from what we often have to do.</p>
<p>One way to make this easier to read would be perhaps this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>tmp1 <span class="ot">&lt;-</span> <span class="fu">j</span>(input_data)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>tmp2 <span class="ot">&lt;-</span> <span class="fu">i</span>(tmp1)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>tmp3 <span class="ot">&lt;-</span> <span class="fu">g</span>(tmp2)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>tmp4 <span class="ot">&lt;-</span> <span class="fu">f</span>(tmp3)</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">f</span>(tmp4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But that’s just too much typing, especially during exploratory phase of data analysis in which we want to get insights into our data as quickly as possible, and when we spend most of our time not writing scripts but playing with our data in the R console!</p>
<p>The pipe approach of <em>tidyverse</em> would make this infinitely easier to write and read (note that we are allowed to even drop the function call parentheses):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>input_data <span class="sc">%&gt;%</span> j <span class="sc">%&gt;%</span> i <span class="sc">%&gt;%</span> g <span class="sc">%&gt;%</span> f <span class="sc">%&gt;%</span> h</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This kind of “data transformation chain” is so frequent that RStudio even provides a built-in shortcut for it:</p>
<ul>
<li>CMD + Shift + M on macOS</li>
<li>CTRL + Shift + M on Windows and Linux</li>
</ul>
<p><strong>Use your newly acquired <code>select()</code> and <code>filter()</code> skills, powered by the <code>%&gt;%</code> piping operator to perform the following transformation on the <code>df</code> metadata table (<code>filter</code>-ing and <code>select</code>-ion operations on the specified columns):</strong></p>
<ol type="1">
<li>filter for “Ancient” individuals (<code>groupAge</code>) who are older than 10000 years (<code>ageAverage</code>), are from Italy (<code>country</code>), and have <code>coverage</code> higher than 3</li>
<li>select <code>sampleId</code>, <code>site</code>, <code>sex</code>, and <code>hgMT</code> and <code>hgYMajor</code> haplogoups</li>
</ol>
<p><strong>As a practice, try to be as silly as you can and write the entire command with as many uses of <code>filter()</code> and <code>select()</code> function calls in sequence as you can. Don’t write the entire pipeline at once, start with one condition, evaluate it, then another another one, etc., inspecting the intermediate results as you’re getting them.</strong> This is the <em>tidyverse</em> way of doing data science.</p>
<p><strong>Hint:</strong> What I mean by this is that the following two commands produce the exact same result:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>new_df1 <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, col1 <span class="sc">==</span> <span class="st">"MatchString"</span>, col2 <span class="sc">&gt;</span> <span class="dv">10000</span>, col3 <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(colX, colY, <span class="fu">starts_with</span>(<span class="st">"ColNamePrefix"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And doing this instead:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>new_df1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(col1 <span class="sc">==</span> <span class="st">"MatchString"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(col2 <span class="sc">&gt;</span> <span class="dv">10000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(col3 <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(colX, colY, <span class="fu">starts_with</span>(<span class="st">"ColNamePrefix"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>This works because “the thing on the left” (which is always a data frame) is placed by the <code>%&gt;%</code> pipe operator as “the first argument of a function on the right” (which again expects always a data frame)!</em></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(groupAge <span class="sc">==</span> <span class="st">"Ancient"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ageAverage <span class="sc">&gt;</span> <span class="dv">10000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"Italy"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(coverage <span class="sc">&gt;</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sampleId, site, sex, hgMT, hgYMajor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  sampleId site              sex   hgMT              hgYMajor
  &lt;chr&gt;    &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt;             &lt;chr&gt;   
1 R7       Grotta Continenza XY    U5b1+16189+@16192 I2a     </code></pre>
</div>
</div>
<p>We could also write the same thing more concisely (not the single <code>filter()</code> call):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(groupAge <span class="sc">==</span> <span class="st">"Ancient"</span>, ageAverage <span class="sc">&gt;</span> <span class="dv">10000</span>, country <span class="sc">==</span> <span class="st">"Italy"</span>, coverage <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sampleId, site, sex, hgMT, hgYMajor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  sampleId site              sex   hgMT              hgYMajor
  &lt;chr&gt;    &lt;chr&gt;             &lt;chr&gt; &lt;chr&gt;             &lt;chr&gt;   
1 R7       Grotta Continenza XY    U5b1+16189+@16192 I2a     </code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Note:</strong> It is always a good practice to split long chains of <code>%&gt;%</code> piping commands into multiple lines, and indenting them neatly one after the other. Readability matters to avoid bugs in your code!</p>
</section>
<section id="exercise-5-more-complex-conditions" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5-more-complex-conditions">Exercise 5: More complex conditions</h2>
<p>You can interpret <code>,</code> in a <code>filter()</code> command as a logical <code>&amp;</code>. In this case of the previous exercise, every single condition must apply to arrive at the individual R7.</p>
<p>Whenever you need to do a more complex operation, such as saying that a variable <code>columnX</code> should have a value <code>"ABC"</code> or <code>"ZXC"</code>, you can write <code>filter(df, columnX == "ABC" | column == "ZXC")</code>. Alternatively, you could write the the same thing using the <code>%in%</code> operator as <code>filter(df, columnX %in% c("ABC", "ZXC"))</code>, which is very useful when you want to match multiple values than you’d be willing to type out by hand (but have them stored in a variable).</p>
<p>Similarly, you can condition on numerical variables. For instance, if you want to condition on variable being <code>varX &lt; 1</code> or <code>varX &gt; 10</code>, you could write <code>filter(df, varX &lt; 1 | var X &gt; 10)</code>.</p>
<p><strong>Practice combining multiple filtering conditions into a <em>tidyverse</em> piping chain by filtering our metadata table to find individuals for which the following conditions hold:</strong></p>
<ul>
<li>they are “Ancient” in <code>groupAge</code></li>
<li><code>country</code> is either “France” or “Canary Islands”</li>
<li><code>coverage</code> either less than 0.1 or more than 3</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(groupAge <span class="sc">==</span> <span class="st">"Ancient"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"France"</span> <span class="sc">|</span> country <span class="sc">==</span> <span class="st">"Canary Islands"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(coverage <span class="sc">&lt;</span> <span class="fl">0.1</span> <span class="sc">|</span> coverage <span class="sc">&gt;</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 32
  sampleId popId  site    country region groupLabel groupAge flag  shapeA colorA
  &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt; 
1 gun011   gun011 Teneri… Canary… North… CanaryIsl… Ancient  0          4 grey  
2 NEO812   NEO812 Grotte… France  Weste… France_Ne… Ancient  0          6 black 
3 NEO813   NEO813 Grotte… France  Weste… France_Ne… Ancient  1d_r…      6 black 
# ℹ 22 more variables: latitude &lt;dbl&gt;, longitude &lt;dbl&gt;, callset &lt;chr&gt;,
#   dataSource &lt;chr&gt;, age14C &lt;dbl&gt;, ageHigh &lt;dbl&gt;, ageLow &lt;dbl&gt;,
#   ageAverage &lt;dbl&gt;, datingSource &lt;chr&gt;, coverage &lt;dbl&gt;, sex &lt;chr&gt;,
#   hgMT &lt;chr&gt;, gpAvg &lt;dbl&gt;, ageRaw &lt;chr&gt;, clusterId &lt;chr&gt;,
#   clusterIBDGlobal &lt;chr&gt;, clusterIBDFine &lt;chr&gt;, hgYMajor &lt;chr&gt;,
#   hgYMinor &lt;chr&gt;, color &lt;chr&gt;, clusterAlias &lt;chr&gt;, shape &lt;dbl&gt;</code></pre>
</div>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="exercise-6-dropping-columns" class="level2">
<h2 class="anchored" data-anchor-id="exercise-6-dropping-columns">Exercise 6: Dropping columns</h2>
<p>This one will be easy. If you want to drop a column from a table, just prefix it with a minus sign (<code>-</code>). Yes, this also works with <code>starts_with()</code> and its friends above, just put <code>-</code> in front of them!</p>
</section>
<section id="exercise-7-renaming-columns" class="level2">
<h2 class="anchored" data-anchor-id="exercise-7-renaming-columns">Exercise 7: Renaming columns</h2>
</section>
<section id="exercise-8-reorganizing-columns" class="level2">
<h2 class="anchored" data-anchor-id="exercise-8-reorganizing-columns">Exercise 8: Reorganizing columns</h2>
</section>
<section id="exercise-9-sorting-tables" class="level2">
<h2 class="anchored" data-anchor-id="exercise-9-sorting-tables">Exercise 9: Sorting tables</h2>
</section>
<section id="exercise-10-mutating-tables" class="level2">
<h2 class="anchored" data-anchor-id="exercise-10-mutating-tables">Exercise 10: Mutating tables</h2>
</section>
<section id="exercise-12-summarizing-tables" class="level2">
<h2 class="anchored" data-anchor-id="exercise-12-summarizing-tables">Exercise 12: Summarizing tables</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./r-bootcamp.html" class="pagination-link" aria-label="R bootcamp">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">R bootcamp</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tidy-ggplot.html" class="pagination-link" aria-label="Data visualization">
        <span class="nav-page-text"><span class="chapter-title">Data visualization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>